---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by seet61.
--- DateTime: 15.09.19 11:33
---

local case = {}

local tap = require('tap')
local db = require('http-test.db')
local config = require('http-test.config.main')

-- Инициализируем приложение для тестирования
local http_test = require('http-test').api(config)
local test = tap.test('registration_test')


