---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by seet61.
--- DateTime: 15.09.19 14:39
---

local log = require('log')
local fio = require('fio')
local config = require('http-test.config.main')
local db = require('http-test.db')
local kv = require('http-test.model.kv').model()

log.debug('package.path: ' .. package.path)
--create folder
fio.mkdir(config.path .. config.instance)

--box configuration
box.cfg {
    pid_file  = config.path .. config.instance .. ".pid",
    log       = "/var/log/tarantool/" .. config.instance .. ".log",
    log_level = config.log_level,
    listen = config.listen_port,
    memtx_memory = config.memtx_memory,
    memtx_max_tuple_size = config.memtx_max_tuple_size,
    memtx_dir = config.path .. config.instance,
    work_dir = config.path .. config.instance,
}

local TEST_CASES = {
    'test.case.registration',
    'test.case.auth',
    'test.case.restore_password',
    'test.case.profile',
    'test.case.social',
    'test.case.complex',
    'test.case.oauth.app',
    'test.case.oauth.oauth',
    'test.case.oauth.scope',
    'test.case.oauth.redirect',
}

local function run()
    for case_index = 1, #TEST_CASES do
        local case = require(TEST_CASES[case_index])
        case.setup()
        for test_index = 1, #case.tests do
            case.before()
            case.tests[test_index]()
            case.after()
        end
        case.teardown()
    end
end

run()
