---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by seet61.
--- DateTime: 15.09.19 10:50
---

-- Конфигурация приложения

return {
    version = '1.0',
    instance = 'master',
    listen_port = 3301,
    http_host = '0.0.0.0',
    http_port = 8800,

    log_level = 7,
    memtx_memory = 268435456,
    memtx_max_tuple_size = 16777216,
    path = "/var/lib/tarantool/",
}