---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by seet61.
--- DateTime: 15.09.19 10:58
---

local log = require('log')

--Создание спейса
local db = {}

local kv = require('http-test.model.kv').model()

function db.create_database()
    local kv_space = box.schema.space.create(kv.SPACE_NAME, {
        if_not_exists = true
    })

    kv_space:format({
        {name=kv.KEY_NAME,type=kv.KEY_TYPE},
        {name=kv.VALUE_NAME,type=kv.VALUE_TYPE},
    })

    kv_space:create_index(kv.PRIMARY_INDEX, {
        type = 'hash',
        parts = {kv.KEY_NAME},
        if_not_exists = true
    })

    log.debug('kv space initialization completed')
end

function db.truncate_database()
    box.space[kv.SPACE_NAME]:truncate()
end

return db